# Generated by Django 4.2.5 on 2023-09-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="membership_type",
            field=models.CharField(
                choices=[("Pro", "Pro"), ("Standard", "Standard"), ("Free", "Free")],
                default="Free",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(name="PayHistory",),
    ]
