# Generated by Django 4.2.5 on 2023-09-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_alter_membership_membership_type_delete_payhistory"),
    ]

    operations = [
        migrations.DeleteModel(name="UserSetting",),
    ]
